services:
  postgres-auth:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres-auth-klp
    environment:
      POSTGRES_USER: kimleepark
      POSTGRES_PASSWORD: kimleepark
      POSTGRES_DB: auth
      TZ: Asia/Seoul
    volumes:
      - klp_postgres_auth_data:/var/lib/postgresql
      - ./init-sql/extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql:ro
    ports:
      - "5432:5432"
    networks:
      - db-net

  postgres-user:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres-user-klp
    environment:
      POSTGRES_USER: kimleepark
      POSTGRES_PASSWORD: kimleepark
      POSTGRES_DB: users
      TZ: Asia/Seoul
    volumes:
      - klp_postgres_user_data:/var/lib/postgresql
      - ./init-sql/extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql:ro
    ports:
      - "5433:5432"
    networks:
      - db-net

  postgres-hub:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres-hub-klp
    environment:
      POSTGRES_USER: kimleepark
      POSTGRES_PASSWORD: kimleepark
      POSTGRES_DB: hub
      TZ: Asia/Seoul
    volumes:
      - klp_postgres_hub_data:/var/lib/postgresql
      - ./init-sql/extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql:ro
    ports:
      - "5434:5432"
    networks:
      - db-net

  postgres-delivery:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres-delivery-klp
    environment:
      POSTGRES_USER: kimleepark
      POSTGRES_PASSWORD: kimleepark
      POSTGRES_DB: delivery
      TZ: Asia/Seoul
    volumes:
      - klp_postgres_delivery_data:/var/lib/postgresql
      - ./init-sql/extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql:ro
    ports:
      - "5435:5432"
    networks:
      - db-net

  postgres-order:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres-order-klp
    environment:
      POSTGRES_USER: kimleepark
      POSTGRES_PASSWORD: kimleepark
      POSTGRES_DB: orders
      TZ: Asia/Seoul
    volumes:
      - klp_postgres_order_data:/var/lib/postgresql
      - ./init-sql/extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql:ro
    ports:
      - "5436:5432"
    networks:
      - db-net

  postgres-notification:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres-notification-klp
    environment:
      POSTGRES_USER: kimleepark
      POSTGRES_PASSWORD: kimleepark
      POSTGRES_DB: notification
      TZ: Asia/Seoul
    volumes:
      - klp_postgres_notification_data:/var/lib/postgresql
      - ./init-sql/extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql:ro
    ports:
      - "5437:5432"
    networks:
      - db-net

  postgres-promotion:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres-promotion-klp
    environment:
      POSTGRES_USER: kimleepark
      POSTGRES_PASSWORD: kimleepark
      POSTGRES_DB: promotion
      TZ: Asia/Seoul
    volumes:
      - klp_postgres_promotion_data:/var/lib/postgresql
      - ./init-sql/extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql:ro
    ports:
      - "5438:5432"
    networks:
      - db-net

  postgres-payment:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres-payment-klp
    environment:
      POSTGRES_USER: kimleepark
      POSTGRES_PASSWORD: kimleepark
      POSTGRES_DB: payment
      TZ: Asia/Seoul
    volumes:
      - klp_postgres_payment_data:/var/lib/postgresql
      - ./init-sql/extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql:ro
    ports:
      - "5439:5432"
    networks:
      - db-net

  postgres-ai:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres-ai-klp
    environment:
      POSTGRES_USER: kimleepark
      POSTGRES_PASSWORD: kimleepark
      POSTGRES_DB: ai
      TZ: Asia/Seoul
    volumes:
      - klp_postgres_ai_data:/var/lib/postgresql
      - ./init-sql/extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql:ro
    ports:
      - "5440:5432"
    networks:
      - db-net

  redis:
    image: redis
    container_name: redis-klp
    volumes:
      - klp_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - db-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.4
    container_name: zookeeper-klp
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - klp-zookeeper-data:/var/lib/zookeeper/data
      - klp-zookeeper-logs:/var/lib/zookeeper/log
    networks:
      - db-net

  kafka:
    image: confluentinc/cp-kafka:7.9.4
    container_name: kafka-klp
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    volumes:
      - klp-kafka-data:/var/lib/kafka/data
    networks:
      - db-net

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui-klp
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8989:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: klp-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - db-net

networks:
  db-net:
    name: db-net

volumes:
  klp_postgres_auth_data:
  klp_postgres_user_data:
  klp_postgres_hub_data:
  klp_postgres_delivery_data:
  klp_postgres_order_data:
  klp_postgres_notification_data:
  klp_postgres_promotion_data:
  klp_postgres_payment_data:
  klp_postgres_ai_data:
  klp_redis_data:
  klp-zookeeper-data:
  klp-zookeeper-logs:
  klp-kafka-data:
