services:
  postgres:
    image: postgres:18
    container_name: postgres-klp
    environment:
      POSTGRES_USER: kimleepark
      POSTGRES_PASSWORD: kimleepark
      POSTGRES_DB: logistics
      TZ: Asia/Seoul
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: redis-klp
    ports:
      - "6379:6379"
