{
 "title": "KLP Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$app_name\", http_route!~\"/actuator/.*|.*/api-docs.*\"}[5m])) by(http_route, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$app_name\", http_route!~\"/actuator/.*|.*/api-docs.*\"}[5m])) by(http_route, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "요청 평균 응답시간",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_route)(rate(http_server_request_duration_seconds_sum{service_name=\"$app_name\", http_route!~\"/actuator/.*|.*/api-docs.*\"}[5m])) / sum by(http_route)(rate(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!~\"/actuator/.*|.*/api-docs.*\"}[5m]))",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "최대 커넥션 수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "hikaricp_connections_max{instance=~\".*\\\\.klp\\\\.local:9464\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "활성 커넥션 수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=~\".*\\\\.klp\\\\.local:9464\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "커넥션을 얻기 위해 대기중인 쓰레드 수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "hikaricp_connections_pending{instance=~\".*\\\\.klp\\\\.local:9464\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Java 프로세스 CPU 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\".*\\\\.klp\\\\.local:9464\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "시스템 CPU 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\".*\\\\.klp\\\\.local:9464\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}