{
 "title": "order cache",
 "time": { "from": "2025-12-08T02:47:48.743Z", "to": "2025-12-08T03:50:50.765Z" },
 "templating": {
  "list": [
   {
    "name": "cache_name",
    "label": "cache_name",
    "query": {
     "query": "label_values(order_mlc_cache_requests_total,cache_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "L1 Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(order_mlc_cache_hits_total{level=\"L1\",\r\n  cache_name=~\"$cache_name\"}[$__range]))\r\n/\r\nsum(rate(order_mlc_cache_requests_total{level=\"L1\",\r\n  cache_name=~\"$cache_name\"}[$__range])))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(order_mlc_cache_l2_hit_total{level=\"L2\",\r\n  cache_name=~\"$cache_name\"}[$__range]))\r\n/\r\nsum(rate(order_mlc_cache_requests_total{level=\"L2\",\r\n  cache_name=~\"$cache_name\"}[$__range])))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Load Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(order_mlc_cache_load_duration_ms_seconds_sum{\r\n  cache_name=~\"$cache_name\"\r\n}[$__range])\r\n/\r\nrate(order_mlc_cache_load_duration_ms_seconds_count{\r\n    cache_name=~\"$cache_name\"\r\n  }[$__range])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}