{
 "title": "Spring Boot Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": "label_values(http_server_request_duration_seconds_count, service_name)"
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_route) (increase(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\"}[$__range]))",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_route)(rate(http_server_request_duration_seconds_sum{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\"}[5m])) / sum by(http_route)(rate(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"5..\", http_route!=\"/actuator/prometheus\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(http_route) (rate(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"2..\", http_route!=\"/actuator/prometheus\"}[5m])) / sum by(http_route) (rate(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(http_route) (rate(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"5..\", http_route!=\"/actuator/prometheus\"}[5m])) / sum by(http_route) (rate(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\"}[5m])) by(http_route, le))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\"}[5m])) by(http_route, le))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_route)(rate(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(type) (rate({compose_service=~\"app-.*\"} | pattern `<date> <time> <_>=<trace_id> <_>=<span_id> <_>=<trace_flags> <type> <_> --- <msg>` | type != \"\" |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Log of All Spring Boot Apps",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".*-service\"}\r\n| pattern `<date> <time> <%level> <_> trace_id=<trace_id> span_id=<span_id> trace_flags=<trace_flags> <msg>`\r\n|= \"$log_keyword\"\r\n| line_format \"date={{.date}}\\ttime={{.time}}\\tlevel={{.level}}\\ttrace_id={{.trace_id}}\\tspan_id={{.span_id}}\\ttrace_flags={{.trace_flags}}\\tmsg={{.msg}}\\tservice_name={{.service_name}}\"\r\n"
    }
   ]
  }
 ]
}