scrape_configs:
  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "192.168.219.101:8010"

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "192.168.219.101:8000"

  - job_name: "gateway-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "192.168.219.101:8080"

  - job_name: "delivery-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "192.168.219.101:8040"

  - job_name: "hub-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "192.168.219.101:8030"

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "192.168.219.101:8050"

  - job_name: "order-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "192.168.219.101:8020"