server:
  port: 9010

spring:
  application:
    name: ai-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 3

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui
