datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      tracesToLogs:
        datasourceUid: ""   # 나중에 Loki 데이터소스 UID 넣으면 trace→log pivot 가능
      tracesToMetrics:
        datasourceUid: "prometheus"
      nodeGraph:
        enabled: true
      search:
        hide: false

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
