{
 "title": "OpenTelemetry for HTTP services",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service_namespace",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,job)"
    }
   },
   {
    "name": "service_name",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=~\"${service_namespace}.*\"},job)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=\"${service_namespace}/${service_name}\"},job)"
    }
   },
   {
    "name": "http_route",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=\"$job\"},http_route)"
    }
   },
   {
    "name": "rateinterval",
    "query": "1m,2m,3m,5m,10m,30m,1h,6h,12h,1d"
   },
   { "name": "predictive_interval", "query": "1h,2h,6h,12h,1d,2d,3d,1w" },
   { "name": "predictive_offset", "query": "1h,2h,6h,12h,1d,2d,3d,1w" },
   { "name": "app_name", "label": "app_name", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  { "title": "RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance metrics overview per service during selected time range",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(http_route)(rate(http_server_request_duration_seconds_count{job=\"$job\",http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (http_route) (increase(http_server_request_duration_seconds_sum{job=\"$job\",http_route=~\"$http_route\"}[$__range])) / sum by(http_route)(increase(http_server_request_duration_seconds_count{job=\"$job\",http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\",http_route=~\"$http_route\"}[$__range])) by(http_route,le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(http_route)(increase(http_server_request_duration_seconds_count{job=\"$job\",http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(http_route) (http_server_request_duration_seconds_count{job=\"$job\",http_route=~\"$http_route\",http_response_status_code=~\"2.*\"}) / sum by(http_route) (http_server_request_duration_seconds_count{job=\"$job\",http_route=~\"$http_route\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS per endpoint over last $rateinterval, $predictive_interval prediction range, $predictive_offset prediction offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_route)(rate(http_server_request_duration_seconds_count{job=\"$job\",http_route=~\"$http_route\"}[$rateinterval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 per endpoint over $rateinterval interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\",http_route=~\"$http_route\"}[$rateinterval])) by(http_route, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 over selected time range",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{application=\"$app_name\", uri!=\"/actuator/prometheus\"}[5m])) by(uri, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Mesh",
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "limit": 20, "serviceMapQuery": "{}", "tableType": "traces" }
   ]
  },
  {
   "title": "Response time distribution in seconds over selected time range",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_server_request_duration_seconds_bucket{job=\"$job\",http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Log of All Spring Boot Apps",
   "type": "logs",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_namespace=\"$service_namespace\", service_name=\"$service_name\"} | line_format `\u001b[1m{{if .level }}{{alignRight 5 .level}}{{else if .severity_text}}{{alignRight 5 .severity_text}}{{end}}\u001b[0m \u001b[90m[{{alignRight 10 .service_instance_id}}{{if .thread_name}}/{{alignRight 20 .thread_name}}{{else if eq \"java\" .telemetry_sdk_language }}                    {{end}}]\u001b[0m \u001b[36m{{if .scope_name }}{{alignRight 40 .scope_name}}{{end}}\u001b[0m {{__line__}} {{if .trace_id}} \u001b[37m\u001b[3m[{{.trace_id}}]{{end}}` | telemetry_sdk_name = `opentelemetry`",
     "maxLines": 80
    }
   ]
  }
 ]
}