CREATE SCHEMA IF NOT EXISTS hub_schema   AUTHORIZATION kimleepark;
CREATE SCHEMA IF NOT EXISTS auth_schema  AUTHORIZATION kimleepark;
CREATE SCHEMA IF NOT EXISTS user_schema  AUTHORIZATION kimleepark;
CREATE SCHEMA IF NOT EXISTS order_schema AUTHORIZATION kimleepark;
